import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fetchCityList, type LeanCity } from "../tools/city.js";

export interface CityDataset {
  updatedAt: string;
  source: string;
  cities: LeanCity[];
}

export type CityOrigin = "github" | "file" | "upstream";

export interface ServedCities {
  origin: CityOrigin;
  updatedAt: string;
  hotOnly: boolean;
  count: number;
  total: number;
  cities: LeanCity[];
}

export interface CityStoreOptions {
  dataDir: string;
  dataBaseUrl: string | null;
  ttlMs: number;
  fetchImpl?: typeof fetch;
  fetchUpstream?: (
    hotOnly: boolean,
  ) => Promise<{ cities: LeanCity[] } | LeanCity[]>;
  remoteTimeoutMs?: number;
}

interface CacheEntry {
  dataset: CityDataset;
  origin: CityOrigin;
  fetchedAt: number;
}

export function filterCities(cities: LeanCity[], hotOnly: boolean): LeanCity[] {
  return hotOnly ? cities.filter((c) => c.hot) : cities;
}

// Tolerant parser for datasets generated by `npm run sync-data` and committed
// under data/cities.json. Unknown fields are dropped; a missing/empty city
// array is treated as "no dataset" so callers can fall back to upstream.
export function parseCityDataset(raw: unknown): CityDataset | null {
  if (raw == null || typeof raw !== "object") return null;
  const obj = raw as Record<string, unknown>;
  if (!Array.isArray(obj.cities) || obj.cities.length === 0) return null;
  const cities: LeanCity[] = [];
  for (const item of obj.cities) {
    if (item == null || typeof item !== "object") continue;
    const c = item as Record<string, unknown>;
    const cityId = typeof c.cityId === "string" ? c.cityId : "";
    const cityName = typeof c.cityName === "string" ? c.cityName : "";
    if (!cityId || !cityName) continue;
    cities.push({
      cityId,
      cityName,
      ...(typeof c.pinyin === "string" && c.pinyin ? { pinyin: c.pinyin } : {}),
      supportSubway: c.supportSubway === true,
      hot: c.hot === true,
    });
  }
  if (cities.length === 0) return null;
  return {
    updatedAt:
      typeof obj.updatedAt === "string" && obj.updatedAt
        ? obj.updatedAt
        : new Date(0).toISOString(),
    source:
      typeof obj.source === "string" && obj.source
        ? obj.source
        : "unknown",
    cities,
  };
}

export class CityStore {
  private readonly options: Required<
    Pick<
      CityStoreOptions,
      "dataDir" | "dataBaseUrl" | "ttlMs" | "fetchImpl" | "fetchUpstream" | "remoteTimeoutMs"
    >
  >;
  private cache: CacheEntry | null = null;

  constructor(options: CityStoreOptions) {
    this.options = {
      dataDir: options.dataDir,
      dataBaseUrl: options.dataBaseUrl,
      ttlMs: options.ttlMs,
      fetchImpl: options.fetchImpl ?? fetch,
      fetchUpstream: options.fetchUpstream ?? fetchCityList,
      remoteTimeoutMs: options.remoteTimeoutMs ?? 8000,
    };
  }

  private async fromUpstream(): Promise<CacheEntry> {
    const result = await this.options.fetchUpstream(false);
    const cities = Array.isArray(result) ? result : result.cities;
    return {
      dataset: {
        updatedAt: new Date().toISOString(),
        source: "chelaile:/wwd/ncitylist",
        cities,
      },
      origin: "upstream",
      fetchedAt: Date.now(),
    };
  }

  private async fromRemote(): Promise<CacheEntry | null> {
    if (!this.options.dataBaseUrl) return null;
    const url = `${this.options.dataBaseUrl}/cities.json`;
    try {
      const res = await this.options.fetchImpl(url, {
        headers: { Accept: "application/json" },
        signal: AbortSignal.timeout(this.options.remoteTimeoutMs),
      });
      if (!res.ok) return null;
      const dataset = parseCityDataset(await res.json());
      if (!dataset) return null;
      return { dataset, origin: "github", fetchedAt: Date.now() };
    } catch {
      return null;
    }
  }

  private async fromFile(): Promise<CacheEntry | null> {
    try {
      const raw = await readFile(
        join(this.options.dataDir, "cities.json"),
        "utf-8",
      );
      const dataset = parseCityDataset(JSON.parse(raw));
      if (!dataset) return null;
      return { dataset, origin: "file", fetchedAt: Date.now() };
    } catch {
      return null;
    }
  }

  async getEntry(
    options: { live?: boolean } = {},
  ): Promise<{ dataset: CityDataset; origin: CityOrigin }> {
    if (options.live) {
      const entry = await this.fromUpstream();
      return { dataset: entry.dataset, origin: entry.origin };
    }

    const now = Date.now();
    if (
      this.cache &&
      this.options.ttlMs > 0 &&
      now - this.cache.fetchedAt < this.options.ttlMs
    ) {
      return { dataset: this.cache.dataset, origin: this.cache.origin };
    }

    const entry =
      (await this.fromRemote()) ??
      (await this.fromFile()) ??
      (await this.fromUpstream());
    this.cache = entry;
    return { dataset: entry.dataset, origin: entry.origin };
  }

  async servedCities(
    hotOnly: boolean,
    live = false,
  ): Promise<ServedCities> {
    const { dataset, origin } = await this.getEntry({ live });
    const cities = filterCities(dataset.cities, hotOnly);
    return {
      origin,
      updatedAt: dataset.updatedAt,
      hotOnly,
      count: cities.length,
      total: dataset.cities.length,
      cities,
    };
  }
}
